#!/usr/bin/env python3

## DataQuest.io
## Python for DataScience: Intermediate
## Python Data Analysis Basics
## PT 9
# Challenge: Summarizing Artwork Gender Data.
# create freq table, summarize info via str.format
# Edited for upload to GitHub

opened_file = open(".../Files/Python/DataQuest MOMA - Museum of Modern Art/artworks_clean.csv")
from csv import reader
read_file = reader(opened_file)
moma_data = list(read_file)
moma_data = moma_data[1:]

gender_freq = {}
for row in moma_data:
	gender = row[5]
	if gender not in gender_freq:
		gender_freq[gender] = 1
	else:
		gender_freq[gender] += 1
		
print(gender_freq)

gender_template = "There are {number:,} artworks by {gend} artists"
# https://docs.python.org/3/tutorial/datastructures.html#looping-techniques
for g, c in gender_freq.items():
	output = gender_template.format(number=c, gend=g)
	print(output)
	
